### ISSUE TITLE
[Olimpiadas] Futebol masculino e feminino

### ISSUE THREAD

**Issue by edsonreis95** [MRAndrade/SportsMobile#4]
Feminino:

- [x] Adicionar ícones: Olimpiadas, Masculino e Feminino

- [x] Adicionar snippet 33 às strings

- [x] Alterar nomes do FloatActionButton

- [x]  Alterar links do FloatActionButton

- [x] Alterar ícones do FloatActionButton

- [x] Mudar data e versão no Gradle

- [x] Gerar APK

- [x] Criar telas Feminino

Masculino:

- [x] Retornar títulos e ícones

- [x] Adicionar ícones: Olimpiadas, Masculino e Feminino

- [x] Adicionar snippet 33 às strings

- [x] Alterar nomes do FloatActionButton

- [x]  Alterar links do FloatActionButton

- [x] Alterar ícones do FloatActionButton

- [x] Mudar data e versão no Gradle

- [x] Gerar APK

- [x] Criar telas Masculino

**Comment by MRAndrade** [comment]
Snippet das Olimpíadas 2016 criado como número 33.
